site_name: UnixToolbox
site_author: "Dmitriy Prigoda"
site_description: >-
  Сборником команд и задач (UnixToolbox)
site_url: "https://D34m0nN0n3.github.io/unixtoolbox/"

repo_name: D34m0nN0n3/unixtoolbox
repo_url: https://github.com/D34m0nN0n3/unixtoolbox
edit_uri: ""

use_directory_urls: false

copyright: Copyright &copy; <a href="https://github.com/D34m0nN0n3">Dmitriy Prigoda</a>.

nav:
    - UnixToolbox: 'index.md'
    - Система: 'system.md'
    - Процессы: 'processes.md'
    - Файловая система: 'file_system.md'
    - Сеть: 'network.md'
    - SSH SCP: 'ssh_scp.md'
    - VPN: 'vpn_with_ssh.md'
    - RSYNC: 'rsync.md'
    - SUDO: 'sudo.md'
    - Шифрование файлов: 'encrypt_files.md'
    - Шифрование разделов: 'encrypt_partitions.md'
    - Сертификаты SSL: 'ssl_certificates.md'
    - CVS: 'cvs.md'
    - SVN: 'svn.md'
    - GIT: 'git.md'
    - Полезные команды: 'useful_commands.md'
    - Установка программного обеспечения: 'install_software.md'
    - Конвертирование медиафайлов: 'convert_media.md'
    - Печать: 'printing.md'
    - Базы данных: 'database.md'
    - Квотирование диска: 'disk_quota.md'
    - Терминальные оболочки: 'shells.md'
    - Создание скриптов: 'scripting.md'
    - Программирование: 'programming.md'
    - Управление конфигурациями: 'configuration_management.md'

plugins:
  - search:
      lang:
        - en
        - ru
  - git-revision-date-localized
  - git-revision-date
  - macros
  - minify:
      minify_html: true
  - with-pdf:
      copyright: https://github.com/D34m0nN0n3
      cover_subtitle: ''
      output_path: UnixToolbox.pdf

extra_css:
  - assets/extra.css

extra_javascript:
  - assets/extra.js
  - assets/tex-mml-chtml.js
  - assets/tablesort.min.js
  - assets/tablesort.js

theme:
  name: material
  custom_dir: material
  language: ru
  features:
    - content.tabs.link
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  palette:
    - scheme: default
      primary: blue grey
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/img/favicon/favicon.png
  logo: assets/img/logo/logo.svg

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  generator: false
  analytics:
    provider: google
    property: G-BT11X31T69
